org.gradle.java.home=C:\\Users\\l\\.jdks\\jbr-21.0.11
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false
kotlin.code.style=official
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.workers.max=1
android.experimental.cacheCompileLibResources=true
nuke.useTestAds=true
